"""
This type stub file was generated by pyright.
"""

from torchvision.transforms import AutoAugmentPolicy, InterpolationMode
from . import functional
from ._transform import Transform
from ._augment import CutMix, JPEG, MixUp, RandomErasing
from ._auto_augment import AugMix, AutoAugment, RandAugment, TrivialAugmentWide
from ._color import ColorJitter, Grayscale, RGB, RandomAdjustSharpness, RandomAutocontrast, RandomChannelPermutation, RandomEqualize, RandomGrayscale, RandomInvert, RandomPhotometricDistort, RandomPosterize, RandomSolarize
from ._container import Compose, RandomApply, RandomChoice, RandomOrder
from ._geometry import CenterCrop, ElasticTransform, FiveCrop, Pad, RandomAffine, RandomCrop, RandomHorizontalFlip, RandomIoUCrop, RandomPerspective, RandomResize, RandomResizedCrop, RandomRotation, RandomShortestSize, RandomVerticalFlip, RandomZoomOut, Resize, ScaleJitter, TenCrop
from ._meta import ClampBoundingBoxes, ConvertBoundingBoxFormat
from ._misc import ConvertImageDtype, GaussianBlur, GaussianNoise, Identity, Lambda, LinearTransformation, Normalize, SanitizeBoundingBoxes, ToDtype
from ._temporal import UniformTemporalSubsample
from ._type_conversion import PILToTensor, ToImage, ToPILImage, ToPureTensor
from ._utils import check_type, get_bounding_boxes, has_all, has_any, query_chw, query_size
from ._deprecated import ToTensor

__all__ = [
    "AutoAugmentPolicy", "InterpolationMode",
    "Transform",
    "CutMix", "JPEG", "MixUp", "RandomErasing",
    "AugMix", "AutoAugment", "RandAugment", "TrivialAugmentWide",
    "ColorJitter", "Grayscale", "RGB", "RandomAdjustSharpness", "RandomAutocontrast", "RandomChannelPermutation", "RandomEqualize", "RandomGrayscale", "RandomInvert", "RandomPhotometricDistort", "RandomPosterize", "RandomSolarize",
    "Compose", "RandomApply", "RandomChoice", "RandomOrder",
    "CenterCrop", "ElasticTransform", "FiveCrop", "Pad", "RandomAffine", "RandomCrop", "RandomHorizontalFlip", "RandomIoUCrop", "RandomPerspective", "RandomResize", "RandomResizedCrop", "RandomRotation", "RandomShortestSize", "RandomVerticalFlip", "RandomZoomOut", "Resize", "ScaleJitter", "TenCrop",
    "ClampBoundingBoxes", "ConvertBoundingBoxFormat",
    "ConvertImageDtype", "GaussianBlur", "GaussianNoise", "Identity", "Lambda", "LinearTransformation", "Normalize", "SanitizeBoundingBoxes", "ToDtype",
    "UniformTemporalSubsample",
    "PILToTensor", "ToImage", "ToPILImage", "ToPureTensor",
    "check_type", "get_bounding_boxes", "has_all", "has_any", "query_chw", "query_size",
    "ToTensor",
]
